import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProviderWrapper } from "@/client/query-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('RootLayout')
  return (
    <QueryClientProviderWrapper>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </QueryClientProviderWrapper>
  );
}
