import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProviderWrapper } from "@/context/query-client-context";
import { RootProvider } from "@/context/root-provider";
import {ReactNode} from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  console.log('RootLayout')
  return (
    <QueryClientProviderWrapper>
      <html lang="en">
        <body className={inter.className}>
          <RootProvider>
            {children}
          </RootProvider>
        </body>
      </html>
    </QueryClientProviderWrapper>
  );
}
